const Discord = require('discord.js');
const client = new Discord.Client();
console.log("Scrpit By Dream");


client.on("ready", () => {
let channel =     client.channels.get("542328854199664661")
setInterval(function() {
channel.send(`spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspamspamcraditspam
spamcraditspamspamcraditspamspamcraditspam`);
}, 30)
})

client.login(process.env.BOT_TOKEN);
