const Discord = require('discord.js');
const client = new Discord.Client();
console.log("Scrpit By Dream");


client.on("ready", () => {
let channel =     client.channels.get("545737556885635132")
setInterval(function() {
channel.send(`farmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRoh
farmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRoh
farmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRoh
farmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRoh
farmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRoh
farmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRoh
farmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRoh
farmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRoh
farmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRoh
farmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRoh
farmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRoh
farmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRoh
farmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRoh
farmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRoh
farmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRoh
farmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRoh
farmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRoh
farmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRoh
farmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRoh
farmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRoh
farmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRoh
farmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRohfarmAboRoh`);
}, 30)
})
client.login(process.env.BOT_TOKEN);
